FROM continuumio/miniconda3 AS build
ENV DEBIAN_FRONTEND noninteractive

COPY ./environment.yml ./requirements.txt ./
RUN apt update && \ 
    apt install -y build-essential libmagic-dev
RUN conda env create -f environment.yml && \
    conda install -c conda-forge conda-pack  && \
    conda-pack -n app -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar && \
    /venv/bin/conda-unpack

FROM debian:buster-slim AS runtime
ENV DEBIAN_FRONTEND noninteractive

WORKDIR /app
RUN mkdir -p /data && \
    apt update && \ 
    apt install -y espeak ffmpeg libespeak1 libmagic-dev && \
    apt-get clean
COPY ./run.py ./
COPY --from=build /venv /venv

ENTRYPOINT ["/bin/bash", "--login", "-c", "./startup.sh"]

# docker build -t local/ttstt_app:latest .
# docker run -v ./app:/app -v ./data:/data -it --rm local/ttstt_app

# TODO figure out why this build/run is not working and fix it. Claims cannot find directories.
