FROM continuumio/miniconda3 AS build

COPY ./environment.yml ./
RUN conda env create -f environment.yml && \
    conda install -c conda-forge conda-pack  && \
    conda-pack -n app -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar && \
    /venv/bin/conda-unpack

FROM ubuntu:latest AS runtime

WORKDIR /app
COPY --from=build /venv /venv
COPY ./run.py ./
RUN mkdir -p /data

ENTRYPOINT ["/bin/bash", "--login", "-c", "./startup.sh"]

# docker build -t local/ttstt_app:latest .
# docker run -v ./app:/app -v ./data:/data -it --rm local/ttstt_app

# TODO figure out why this build/run is not working and fix it. Claims cannot find directories.
