name: app

channels:
  - defaults
  - anaconda
  - conda-forge 

dependencies:
  - python=3.7
  - python-docx
  - pyaudio
  - python-slugify
  - gtts
  - pydub
  - ffmpeg
  - pip
  - pip:
      - -r requirements.txt

# conda env create -f environment.yml
# 
# conda activate myenv
# conda env update --file local.yml --prune